baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Unnerved Reality'

theme = "unnervedTheme"

[menu]
  [[menu.main]]
    name = "ğŸš Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "ğŸ“• Logs"
    pre = "pen-tool"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3
