baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Unnerved Reality'

theme = "unnervedTheme"

disqusShortname = 'unnerved'

[menu]
  [[menu.main]]
    name = "ğŸš Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "ğŸ“• Logs"
    pre = "pen-tool"
    url = "/posts/"
    weight = 2
   [[menu.main]]
    name = "ğŸ—ƒ Categorie"
    pre = "tag"
    url = "/tags/"
    weight = 3
    [[menu.main]]
    name = "Pagina"
    pre = "pagina"
    url = "/prova/"
    weight = 4

